pipeline {
    agent any
    environment {
        CREDENTIALS = credentials('9dffe2e7-f3fb-4259-b72b-f6694ada5b54')
    }

    stages {
        stage("Build the Docker Image") {
            steps {
                script {
                    sh "docker build -t docker.io/achref2h/static-app:v1 -f 'Practise third attempt/Dockerfile' ."
                }
            }
        }
        
        stage("Login and Push to Docker Hub") {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: '9dffe2e7-f3fb-4259-b72b-f6694ada5b54', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
                        sh "docker push docker.io/achref2h/static-app:v1"
                    }
                }
            }
        }
        stage("Deploy to k8s") {
            steps {
                sh "minikube start"
                sh "kubectl create deployment my-app-deployment --image=docker.io/achref2h/static-app:v1 --replicas=3 --port=80"
                sh "kubectl expose deployment my-app-deployment --type=NodePort --name=my-nodeport-service --port=80 --target-port=80"
            }
        }
    }
}
